AddtaskCommand , Task 기능 분리
plm3033/bot pull request #6
Opened 2024-02-14 06:32 UTC by plm3033

AddTaskCoommand 클래스에서 기능하던 Json 을 Task 에 입력하는 기능을 Task 클래스로 이전.

2024-02-14 06:34 UTC, plm3033 commented
이게 이렇게 하는게 맞겠냐? 확인해봐

2024-02-16 06:45 UTC, GoodGoodJM requested changes
프롬프트를 이용해서 제대로 된 json을 받아와 `val jsonGroupData = "[" + chatMessage + "]"` 같은 잘못된 부분을 수정하는건 다른 태스크에서 진행하는 걸까요?

2024-02-16 06:48 UTC, plm3033 commented
Json 데이터를 받아오는 코드를 새로운 태스크를 만들어서 수정하겠습니다.

2024-02-18 05:25 UTC, GoodGoodJM approved these changes
LGTM

2024-02-18 05:25 UTC, merged