HIMM-13
plm3033/bot pull request #8
Opened 2024-02-14 07:21 UTC by plm3033

클래스 명 수정 및 삭제. 의미에 맞는 class 명 적용, 사용하지 않는 class 삭제 (NewTaskCommand.class).

2024-02-16 06:48 UTC, GoodGoodJM requested changes
의도가 불분명하거나 일반적이지 않은 네임의 수정이 필요할 것 같습니다.

2024-02-16 06:48 UTC, GoodGoodJM commented on src/main/kotlin/testDiscordBot/bot/discordAPI/command/AiPromptDevice.kt
> +class AiPromptDevice (
Device는 일반적이지 않은 클레스 네임처럼 보입니다.

2024-02-16 06:48 UTC, GoodGoodJM commented on src/main/kotlin/testDiscordBot/bot/discordAPI/command/BeanRegister.kt
> +annotation class BeanRegister(val prefix :String)
의도를 알기 힘든 어노테이션 네임같습니다. Command  정도가 어떨까요?

2024-02-16 06:49 UTC, plm3033 commented on src/main/kotlin/testDiscordBot/bot/discordAPI/command/AiPromptDevice.kt
> +class AiPromptDevice (
Device 클래스 명 , 확인 후 수정 하도록 하겠습니다.

2024-02-16 06:50 UTC, plm3033 commented on src/main/kotlin/testDiscordBot/bot/discordAPI/command/BeanRegister.kt
> +annotation class BeanRegister(val prefix :String)
Command 로 수정하도록 하겠습니다.

2024-02-18 06:07 UTC, GoodGoodJM approved these changes
LGTM

2024-02-18 06:07 UTC, merged